config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"

  resources :users do
    resources :villagers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :villagers, dependent: :destroy
  # delete user, then delete user's villagers

  validates_presence_of :username
  validates_uniqueness_of :email
end

app/models/villager.rb
class Villager < ApplicationRecord
    belongs_to :user

    validates_presence_of :img_url

    PERSONALITY_CHOICES = ["♂ lazy", "♂ jock", "♂ cranky", "♂ smug", "♀ normal", "♀ peppy", "♀ snooty", "♀ big sister"]
    SPECIES_CHOICES = ["alligator/crocodile", "bear/cub", "bird", "bull/cow", "deer/reindeer", "dog", "frog", "horse", "octopus", "ostrich", "robot", "special", "other"]
    GENDER = ["male", "female"]
    STATUS_CHOICES = ["♥ fav", "⭑ want", "✓ have", "✗ moved out", "↯ dislike", "☠ hate"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    # adds name field to devise
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
     root_path
   end

    protected
         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
         end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]
    
    # GET /resource/sign_up
    # def new
    #   super
    # end
  
    # POST /resource
    def create
      super
    end
  
    # GET /resource/edit
    # def edit
    #   super
    # end
  
    # PUT /resource
    def update
      super
    end
  
    # DELETE /resource
    # def destroy
    #   super
    # end
  
    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end
  
    protected
  
    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :password_confirmation])
    end
  
    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :password_confirmation])
    end
  
    # The path used after sign up.
    def after_sign_up_path_for(resource)
      root_path
    end
  
    # The path used after sign up for inactive accounts.
    def after_inactive_sign_up_path_for(resource)
      super(resource)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action: :find_user, only: [:show, :edit, :update, :destroy]
    # before_action: :currently_logged_in, only: [:edit, :update, :destroy]
    
        def index
            @users = User.all
        end
    
        def create
            @user = User.new(user)
    
            if @user.save
                flash.notice = "welcome!"
                session[:user_id] = @user.id
    
                redirect_to root_path
            else 
                @user.errors.full_messages

                render :new 
            end
        end
    
        def new
            @user = User.new
        end
    
        def edit
        end
    
        def show
        end
    
        def update
            if @user.update(user_params)
    
                redirect_to @user
            else
                render :edit
            end
        end
    
        def destroy
            @user.destroy
            
            redirect_to login_path
        end
    
    private
        def find_user
            @user = User.find_by(params[:id])
        end
    
        def currently_logged_in
            unless logged_in?
                flash.alert = "oops, please log in"
    
                redirect_to login_path
            end
        end
    
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end
end 

app/controllers/villagers_controller.rb
class VillagersController < ApplicationController
    before_action :find_villagers, only: [:show, :edit, :update, :destroy]

    def index
        @villagers = current_user.villagers
    end

    def new
       @villager = Villager.new
    end
    
    def create
        @villager = current_user.villagers.build(villager_params)
        @villager.user_id = current_user.id
        
        if @villager.save
            flash.notice = "villager successfully added"

            redirect_to user_villager_path(current_user, @villager)
        else
            @villager.errors.full_messages

            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @villager.update(villager_params)

            redirect_to user_villager_path(current_user, @villager)
        else
            @villager.errors.full_messages
            
            render :edit
        end
    end

    def destroy
        @villager.destroy
    
        redirect_to root_path
    end

    private 
        def find_villagers
            @villager = Villager.find(params[:id])
        end

        def villager_params
            params.require(:villager).permit(:user_id, :name, :species, :gender, :personality, :birthday, :catchphrase, :status, :img_url, :comments)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/registration.css">

<% if current_user %> 
    <div class="wrapper">
            <div class="registration-container-left">
                <%= button_to "log out", destroy_user_session_path, method: "delete", :class => "logout-button"%><br><br>
                
                <div class="nav">
                    <input type="checkbox" id="nav-check">
                    <div class="nav-button">
                        <label for="nav-check">
                            <span>+</span>
                        </label>
                </div>

                <div class="nav-menu">
                    <%= link_to "add new villager" , new_user_villager_path(current_user), {:class => "nav-links"}%>
                </div>
            </div>
        </div>

            <div class="registration-container-right";>
                <div class="registration-right-content">
                    <div class="card">
                        <center><h2><%= current_user.username %>'s villagers</h2>

                        <% if current_user.villagers.first.nil? %>
                            <p>Hmmm, no villagers here. . .<br><br> 
                            Love cats with glasses like ✧Raymond✧? Not the biggest fan of ⋆Beardo⋆?<br>
                            Click "add villager" to track all your fav friends.</p>
                        <% else %>
                            <% all_villagers = current_user.villagers %>
                            <% all_villagers.each do |villager| %>
                                <h3>✪ <%= villager.name %>, <%= villager.status %> </h3> 
                                <%= link_to "view" , user_villager_path(current_user, villager), {:class => "view"}%><br>
                            <% end %>
                        <% end %></center>
                    </div>
                </div>
            </div>
    </div>
    
<% else %>
    <%= render "partials/registration_links" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friend Crossing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Alfa+Slab+One&family=Raleway:wght@200;300;500;600&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <div class="header">
      <%= image_tag("nook-inc-logo.png", height: "70", width: "70") %>
      <h1>Friend Crossing</h1>
    </div>
  </body>
</html>

app/views/partials/_registration_links.html.erb
<div class="wrapper">
        <div class="registration-container-left";>
        </div>

        <div class="registration-container-right";>
            <div class="registration-card">
                <h2>go ahead, finesse your friends</h2>

                <div class="registration-links">
                    <div class="row">
                        <%= link_to "sign up", new_user_registration_path, {:class => "registration"} %>
                        <%= link_to "log in", new_user_session_path, {:class => "registration"} %>
                    </div>
                </div>
            </div>  
        </div>
    </div>

app/views/villagers/edit.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/villager.css">

<% if @villager.user_id == current_user.id %> 
    <div class="wrapper">
            <div class="container-left">
            <%= button_to "log out", destroy_user_session_path, method: "delete", :class => "logout-button"%><br><br>
                
                <div class="nav-menu">
                    <%= link_to "back", :back, { :class => "nav-links" } %>
                </div>
            </div>

            <div class="container-right";>
                <div class="right-content">
                    <div class="card">
                        <center><h2>edit <%= @villager.name %></h2></center>

                        <%= form_with model: @villager, url: user_villager_path(current_user, @villager), method: "patch" do |f| %>
                            <%= f.text_field :img_url, placeholder: "photo url of villager ٭" %><br><br>
                            <%= f.text_field :name, placeholder: "villager's name" %>

                            <%= f.collection_select :gender, Villager::GENDER, :to_s, :to_s %> <%= f.collection_select :status, Villager::STATUS_CHOICES, :to_s, :to_s %><br><br>

                            <%= f.text_field :birthday, placeholder: "villager's birthday" %>

                            <div class="margins">
                                <p><%= f.label "personality" %>: </p>
                                <%= f.collection_select :personality, Villager::PERSONALITY_CHOICES, :to_s, :to_s %>
                                <p><%= f.label "species" %>: </p>
                                <%= f.collection_select :species, Villager::SPECIES_CHOICES, :to_s, :to_s %><br><br>
                            </div>

                            <%= f.text_field :catchphrase, placeholder: "villager's catchphrase" %><br><br>

                            <%= f.text_field :comments, placeholder: "comments" %><br><br>
                        
                            <center><%= f.submit "edit" %></center>
                        <% end %>
                    </div>
                </div>
            </div>
    </div>
    
<% else %>
    <%= render "partials/registration_links" %>
<% end %>

app/views/villagers/new.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/villager.css">

<% if current_user %> 
    <div class="wrapper">
            <div class="container-left">
            <%= button_to "log out", destroy_user_session_path, method: "delete", :class => "logout-button"%><br><br>
                
                <div class="nav-menu">
                    <%= link_to "back", :back, { :class => "nav-links" } %>
                </div>
            </div>

            <div class="container-right";>
                <div class="right-content">
                    <div class="card">
                        <center><h2>add a villager</h2></center>

                        <%= form_with model: @villager, url: user_villagers_path(current_user, @villager), method: "post" do |f| %>
                            <%= f.text_field :img_url, placeholder: "photo url of villager ٭" %><br><br>
                            <%= f.text_field :name, placeholder: "villager's name" %>

                            <%= f.collection_select :gender, Villager::GENDER, :to_s, :to_s %> <%= f.collection_select :status, Villager::STATUS_CHOICES, :to_s, :to_s %><br><br>

                            <%= f.text_field :birthday, placeholder: "villager's birthday" %>

                            <div class="margins">
                                <p><%= f.label "personality" %>: </p>
                                <%= f.collection_select :personality, Villager::PERSONALITY_CHOICES, :to_s, :to_s %>
                                <p><%= f.label "species" %>: </p>
                                <%= f.collection_select :species, Villager::SPECIES_CHOICES, :to_s, :to_s %><br><br>
                            </div>

                            <%= f.text_field :catchphrase, placeholder: "villager's catchphrase" %><br><br>

                            <%= f.text_field :comments, placeholder: "comments" %><br><br>
                        
                            <center><%= f.submit "add" %></center>
                        <% end %>
                    </div>
                </div>
            </div>
    </div>
    
<% else %>
    <%= render "partials/registration_links" %>
<% end %>

app/views/villagers/show.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/villager.css">

<% if @villager.user_id == current_user.id %>
    <div class="wrapper">
            <div class="container-left">
            <%= button_to "log out", destroy_user_session_path, method: "delete", :class => "logout-button"%><br><br>
                
                <div class="nav">
                    <input type="checkbox" id="nav-check">
                    <div class="nav-button">
                        <label for="nav-check">
                            <span>+</span>
                        </label>
                </div>

                    <div class="nav-menu">
                        <%= link_to "home", root_path, { :class => "nav-links" } %><br><br><br>
                        <%= link_to "add new villager" , new_user_villager_path(current_user), {:class => "nav-links"}%><br><br><br>
                        <%= link_to "edit villager" , edit_user_villager_path(current_user, @villager), {:class => "nav-links"}%><br><br><br>

                        <div class="border">
                            <%= button_to "delete", user_villager_path(current_user, @villager), method: "delete", :class => "button" %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-right";>
                <div class="right-content">
                    <div class="card">
                        <center><h2><%= @villager.name %></h2>
                       <div class="margin-less">
                            <h3>"<%= @villager.catchphrase %>"<h3>
                        </div>
                        <%= image_tag(@villager.img_url, height: "130rem", width: "100rem") %></center>

                        <div class="villager-info">
                            <h3><%= @villager.birthday %><br><br>
                            <%= @villager.gender %> | <%= @villager.species %> | <%= @villager.personality %><br>
                            <%= @villager.status %> | <%= @villager.comments %></h3>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    
<% else %>
    <%= render "partials/registration_links" %>
<% end %>